default_language_version:
  python: python3.12

default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: LICENSE
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy .
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort .
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: poetry run flake8 .
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black .
        types: [python]
        language: system
