name: deploy

on:
  workflow_run:
    workflows: ["test"]
    types:
      - completed
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Set docker image name and tag
        env:
          DOCKER_IMAGE_NAME: ${{ vars.DOCKER_IMAGE_NAME }}
          DOCKER_IMAGE_TAG: "${{ github.sha }}-${{ github.run_number }}"
        run: |
          sed -i 's#repository: app#repository: ${{ env.DOCKER_IMAGE_NAME }}#' "./charts/app/values.yaml"
          sed -i 's#tag: "latest"#tag: "${{ env.DOCKER_IMAGE_TAG }}"#' "./charts/app/values.yaml"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        env:
          DOCKER_IMAGE_NAME: ${{ vars.DOCKER_IMAGE_NAME }}
          DOCKER_IMAGE_TAG: "${{ github.sha }}-${{ github.run_number }}"
        with:
          push: true
          tags: "${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}"

  deploy:
    runs-on: ubuntu-latest
    needs: [release, build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy to Kubernetes Cluster
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          HELM_REPO_URL: ${{ vars.HELM_REPO_URL }}
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBE_CONFIG" | base64 --decode > $HOME/.kube/config
          helm repo add defrepo $HELM_REPO_URL
          helm upgrade --install my-app defrepo/app
